apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-react
  labels:
    app: todo-react
spec:
  selector:
    matchLabels:
      app: todo-react
  replicas: 2
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 2
  template:
    metadata:
      labels:
        app: todo-react
    spec:
      containers:
        - image: venkat271997/react-todo
          imagePullPolicy: Always
          name: todo-react
          ports:
          - containerPort: 80